apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 1
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "feliperomao07/hello-go:v8.3"
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000 # Porta do container
            periodSeconds: 3
            failureThreshold: 1
            initialDelaySeconds: 10 # Aguardar 10 segundo para começar a verificar
          
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000 # Porta do container
            periodSeconds: 5
            failureThreshold: 3
            timeoutSeconds: 1
            successThreshold: 1
            initialDelaySeconds: 15 # Aguardar 10 segundo para começar a verificar

          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret
          volumeMounts:
            - mountPath: "/go/myfamily"
              name: config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
              - key: members
                path: "family.txt"
