apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql-h
  replicas: 4
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            # - name: MYSQL_ALLOW_EMPTY_PASSWORD
            #   value: false
            # - name: MYSQL_RANDOM_ROOT_PASSWORD
            #   value: false